version: '3.1'

networks:
  movie-net:
    driver: bridge

volumes:
  moviedb:

services:
  moviedb:
    image: mongo:5.0.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    volumes:
      - moviedb:/data/db
    networks:
      - movie-net
  app:
    image: rogeriostos/movies:v1
    restart: always
    ports:
      - 8181:8181
    environment:
      MONGODB_URI: mongodb://mongouser:mongopwd@moviedb:27017/admin
    volumes:
      - moviedb:/data/db
    depends_on:
      - moviedb
    networks:
      - movie-net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopwd@moviedb:27017/
    depends_on:
      - moviedb
    networks:
      - movie-net